name: Run Unit Tests on PR

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run .NET Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src

      - name: Run Unit Tests with Report
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx"
        working-directory: ./src

      - name: Publish Test Results to PR
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Unit Tests
          path: ./src/TestResults.trx
          reporter: dotnet-trx

      - name: Run Tests with Coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./src/TestResults
        working-directory: ./src

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/TestResults/*/coverage.cobertura.xml
          flags: unittests
          fail_ci_if_error: true
